### ISSUE TITLE
Can not install Android on Windows

### ISSUE THREAD

**Issue by blackjyn** [miurahr/aqtinstall#254]
Tried 
`aqt install -O Qt6 6.1.0 windows android android_arm64_v8a`

but giving error:
```
2021-05-29 04:54:07,238 - aqt - INFO - aqtinstall(aqt) v0.9.2 on Python 3.8.3 [C
Python MSC v.1924 64 bit (AMD64)]
2021-05-29 04:54:07,238 - aqt - WARNING - Specified Qt version is unknown: 6.1.0
.
2021-05-29 04:54:07,238 - aqt - WARNING - Some of specified modules are unknown.

2021-05-29 04:54:08,608 - aqt - ERROR - Specified packages are not found while p
arsing XML of package information!
2021-05-29 04:54:08,608 - aqt - DEBUG - <Updates>
 <ApplicationName>{AnyApplication}</ApplicationName>
 <ApplicationVersion>1.0.0</ApplicationVersion>
 <Checksum>true</Checksum>
 <PackageUpdate>
  <Name>qt.qt6.610.android</Name>
  <DisplayName>Android</DisplayName>
  <Description>Qt 6.1.0 Prebuilt Components for Android armv7, arm64-v8a, x86 an
d x86_64</Description>
  <Version>6.1.0-0-202105041014</Version>
  <ReleaseDate>2021-05-04</ReleaseDate>
  <Dependencies>qt.tools.qtcreator, qt.qt6.610.doc, qt.qt6.610.examples, qt.qt6.
610.android_arm64_v8a, qt.qt6.610.android_armv7, qt.qt6.610.android_x86, qt.qt6.
610.android_x86_64</Dependencies>
  <AutoDependOn/>
  <Default>false</Default>
  <Script>installscript.qs</Script>
  <SortingPriority>270</SortingPriority>
  <DownloadableArchives/>
  <UpdateFile OS="Any" UncompressedSize="0" CompressedSize="0"/>
  <SHA1>9e1df1c15d41d407a8e2288e1b61769091e97246</SHA1>
 </PackageUpdate>
 <SHA1>9e1df1c15d41d407a8e2288e1b61769091e97246</SHA1>
 <MetadataName>2021-05-04-1014_meta.7z</MetadataName>
</Updates>

2021-05-29 04:54:08,608 - aqt - ERROR - Configuration file generation error: (2,
 'No such file or directory')
```

**Comment by miurahr** [comment]
```aqt install -O Qt6 6.1.0 windows android android```

**Comment by blackjyn** [comment]
I got error still , 
Im on Windows 8.1 x64
![aqt cant install android](https://user-images.githubusercontent.com/6046191/120059713-41a96e80-c07d-11eb-8f95-ca09051f949e.png)

**Comment by blackjyn** [comment]
Previously I also ran both 
```
aqt install -O Qt6Xx 6.1.0 windows desktop win64_mingw81
aqt install -O Qt6Xx 6.1.0 windows desktop win64_msvc2019_64
```
and suceed.

Failed on ANdroid only

**Comment by miurahr** [comment]
# v1.0.0 has a fix

## Fixed
- Fix Qt6/Android installation handling.(#193, #200)

# v1.1.0 has an improvement

## Added
- Patching android installation for Qt6

**Comment by blackjyn** [comment]
Oh my bad.
This issue persists because I was using aqt v 0.9.2 and forgot to install to latest version.

After installing to the latest version via :
`pip install aqtinstall -U`

**all the android toolchains can be installed, so these are now working**

```
aqt install -O Qt6Xx 6.1.0 windows android android_x86_64
aqt install -O Qt6Xx 6.1.0 windows android android_arm64_v8
aqt install -O Qt6Xx 6.1.0 windows android android_x86
aqt install -O Qt6Xx 6.1.0 windows android android_armv7
```


**however still this cmd is not working: `aqt install -O Qt6Xx 6.1.0 windows android android`**
![image](https://user-images.githubusercontent.com/6046191/121291102-e9daf500-c911-11eb-8c72-c423b834dbff.png)

so , still for android we gotta mentioned specific arch
